# Menu latéral structuré pour Hugo Book

[[book]]
  name = "À PROPOS DU COURS"
  identifier = "apropos"
  weight = 1

[[book]]
  name = "Présentation"
  url = "/presentation/"
  parent = "apropos"
  weight = 2
[[book]]
  name = "Feuille de route"
  url = "/feuille-de-route/"
  parent = "apropos"
  weight = 3
[[book]]
  name = "Évaluation"
  url = "/evaluation/"
  parent = "apropos"
  weight = 4
[[book]]
  name = "Ressources"
  url = "/ressources/"
  parent = "apropos"
  weight = 5
[[book]]
  name = "FAQ"
  url = "/faq/"
  parent = "apropos"
  weight = 6
[[book]]
  name = "Crédits"
  url = "/credits/"
  parent = "apropos"
  weight = 7

[[book]]
  name = "Module 1"
  identifier = "module1"
  weight = 10
[[book]]
  name = "Activités 1.0 et 1.1"
  url = "/modules/module1/activites-1-0-1-1/"
  parent = "module1"
  weight = 11
[[book]]
  name = "Activité 1.2"
  url = "/modules/module1/activite-1-2/"
  parent = "module1"
  weight = 12
[[book]]
  name = "Exercices 1.1"
  url = "/modules/module1/exercices-1-1/"
  parent = "module1"
  weight = 13
[[book]]
  name = "Travail noté 1"
  url = "/modules/module1/travail-note-1/"
  parent = "module1"
  weight = 14

[[book]]
  name = "Module 2"
  identifier = "module2"
  weight = 20
[[book]]
  name = "Activité 2.1"
  url = "/modules/module2/activite-2-1/"
  parent = "module2"
  weight = 21
[[book]]
  name = "Activité 2.2"
  url = "/modules/module2/activite-2-2/"
  parent = "module2"
  weight = 22
[[book]]
  name = "Activité 2.3"
  url = "/modules/module2/activite-2-3/"
  parent = "module2"
  weight = 23
[[book]]
  name = "Exercices 2.1"
  url = "/modules/module2/exercices-2-1/"
  parent = "module2"
  weight = 24
[[book]]
  name = "Activité 2.4"
  url = "/modules/module2/activite-2-4/"
  parent = "module2"
  weight = 25
[[book]]
  name = "Exercices 2.2"
  url = "/modules/module2/exercices-2-2/"
  parent = "module2"
  weight = 26
[[book]]
  name = "Travail noté 2"
  url = "/modules/module2/travail-note-2/"
  parent = "module2"
  weight = 27

[[book]]
  name = "Module 3"
  identifier = "module3"
  weight = 30
[[book]]
  name = "Activité 3.1"
  url = "/modules/module3/activite-3-1/"
  parent = "module3"
  weight = 31
[[book]]
  name = "Activité 3.2"
  url = "/modules/module3/activite-3-2/"
  parent = "module3"
  weight = 32
[[book]]
  name = "Activité 3.3"
  url = "/modules/module3/activite-3-3/"
  parent = "module3"
  weight = 33
[[book]]
  name = "Exercices 3.1"
  url = "/modules/module3/exercices-3-1/"
  parent = "module3"
  weight = 34
[[book]]
  name = "Travail noté 3"
  url = "/modules/module3/travail-note-3/"
  parent = "module3"
  weight = 35
[[book]]
  name = "Activité 3.4"
  url = "/modules/module3/activite-3-4/"
  parent = "module3"
  weight = 36
[[book]]
  name = "Activité 3.5"
  url = "/modules/module3/activite-3-5/"
  parent = "module3"
  weight = 37

[[book]]
  name = "Module 4"
  identifier = "module4"
  weight = 40
[[book]]
  name = "Activité 4.1"
  url = "/modules/module4/activite-4-1/"
  parent = "module4"
  weight = 41
[[book]]
  name = "Activité 4.2"
  url = "/modules/module4/activite-4-2/"
  parent = "module4"
  weight = 42
[[book]]
  name = "Exercices 4.1"
  url = "/modules/module4/exercices-4-1/"
  parent = "module4"
  weight = 43
[[book]]
  name = "Travail noté 4"
  url = "/modules/module4/travail-note-4/"
  parent = "module4"
  weight = 44

[[book]]
  name = "Module 5"
  identifier = "module5"
  weight = 50
[[book]]
  name = "Activité 5.1"
  url = "/modules/module5/activite-5-1/"
  parent = "module5"
  weight = 51
[[book]]
  name = "Activité 5.2"
  url = "/modules/module5/activite-5-2/"
  parent = "module5"
  weight = 52
[[book]]
  name = "Exercices 5.1"
  url = "/modules/module5/exercices-5-1/"
  parent = "module5"
  weight = 53
[[book]]
  name = "Travail noté 5"
  url = "/modules/module5/travail-note-5/"
  parent = "module5"
  weight = 54

[[book]]
  name = "Projet"
  url = "/modules/projet/"
  weight = 60
